site_name: The Modern Networks Compass
site_url: https://modernnetworksnav.com/
nav:
    - Home: index.md
    - Hitless Upgrades: hitless-upgrades/hitless-upgrades-in-campus.md
theme:
  name: material