site_name: The Modern Networking Model
site_url: https://modernnetworksnav.com/
nav:
    - Home: index.md
    # - Network Designs: []
    - Automation:
      - Fundamentals: 
        - Overview: network-automation/fundamentals/fundamentals.md
        - Git: network-automation/fundamentals/git.md
        - VS Code: network-automation/fundamentals/vscode.md
        - YAML: network-automation/fundamentals/yaml.md
        - Ansible: network-automation/fundamentals/ansible.md
    - Operations:
      - Hitless Upgrades: hitless-upgrades/hitless-upgrades-in-campus.md
      # - Migrations: 
theme:
  name: material