site_name: The Modern Networking Model
site_url: https://modernnetworksnav.com/
nav:
    - Home: index.md
    # - Network Designs: []
    - Automation: []
    - Operations:
      - Hitless Upgrades: hitless-upgrades/hitless-upgrades-in-campus.md
      # - Migrations: 
theme:
  name: material